name: Build make_it

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source/requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile source/make_it.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: make_it-build
          path: dist/make_it
